# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/grupo8',
                'doc_host': 'https://PriscilaNC.github.io',
                'git_url': 'https://github.com/PriscilaNC/grupo8',
                'lib_path': 'grupo8'},
  'syms': {'grupo8.core': {'grupo8.core.foo': ('core.html#foo', 'grupo8/core.py')}}}
