---
title: "Clasificador de Sonido"
description: "Ejemplo de modelo pre-entrenado funcionando"
format: html
---

<div id="p5-sketch">
  <div id="canvas-container"></div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.4/p5.min.js"></script>
<script src="https://unpkg.com/ml5@latest/dist/ml5.min.js"></script>
 
 
 
<script>
(function() {
  const sketch = (p) => {let classifier;
let modelLoaded = 'https://teachablemachine.withgoogle.com/models/3FDQ0h2-1/';
let words = ["Ruido de fondo", "cristal", "disparo"];
let predictedWord = "";

function preload(){
  // Cargar el modelo de SpeechCommands correctamente
  let options = { probabilityThreshold: 0.7 };
  classifier = ml5.soundClassifier(modelLoaded, options);
}

function setup() {
  createCanvas(650, 450);
  // Classificar el sonido del micrófono en tiempo real
  classifier.classify(gotResult);
}

// Una función que se ejecuta cuando tenemos resultados
function gotResult(error, results) {
  if (error) {
    console.error(error);
    return;
  }
  // Los resultados están en un array ordenado por confianza
  console.log(results);
  predictedWord = results[0].label;
}

// Función para mostrar las palabras en el canvas
function displayWords() {
  textAlign(CENTER, CENTER);
  textSize(32);
  fill(96);
  text("Say one of these words!", width / 2, 40);
  let x = 125;
  let y = 150;
  // Palabras en 3 columnas de 6 filas
  for (let i = 0; i < words.length; i++) {
    fill(158);
    text(words[i], x, y);
    y += 50;
    if ((i + 1) % 6 === 0) {
      x += 200;
      y = 150;
    }
  }
}

function draw() {
  background(250);
  // Llamar a la función para mostrar las palabras de fondo
  displayWords();
  // Mostrar la palabra predicha en el canvas
  if (predictedWord !== "") {
    fill(211, 107, 255);
    textAlign(CENTER, CENTER);
    textSize(64);
    text(predictedWord, width / 2, 90);
  }
}


  }; 
    new p5(sketch);
})();
</script>
